version: '3'
services:
  nginx:
    image: nginx:1.13.5-alpine
    ports: 
      - "80:80"
    depends_on:
      - app
    volumes: 
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./data:/var/www
  app:
    build: ./php
    volumes:
      - ./data:/var/www
      - ./php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql
  mysql:
    build: ./db
    volumes:
      - "./mysql:/var/lib/mysql"
      - ./data:/var/www
    environment:
      - MYSQL_ROOT_PASSWORD=password
    command: --innodb-use-native-aio=0
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=password
    restart: always
    depends_on:
      - mysql
    ports:
      - 8080:80